### ISSUE TITLE
Helm installation fails due to "apoc.generate.ba already registered"

### ISSUE THREAD

**Issue by felipeazv** [neo4j-contrib/neo4j-helm#139]
I am currently facing an issue with the helm chart version `4.1.3-1`.

The deployment fails with the following message:
 
"Caused by: org.neo4j.internal.kernel.api.exceptions.Procedure Exception: Unable to register procedure, because the name apoc.generate.ba is already in use" 

Obs: it is a fresh installation so there were no plugins previously installed.

The whole deployment log:

Warning: Some files inside "/plugins" are not writable from inside container. Changing folder owner to neo4j.
Warning: Some files inside "/data" are not writable from inside container. Changing folder owner to neo4j.
Changed password for user 'neo4j'.
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Installing Plugin 'apoc' from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.4/apoc-4.1.0.4-all.jar to /plugins/apoc.jar 
Applying default values for plugin apoc to neo4j.conf
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /data/logs
  plugins:      /plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2020-11-19 10:37:13.977+0000 WARN  Unrecognized setting. No declared setting with name: metrics.graphite.server
2020-11-19 10:37:13.980+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.minimum_core_cluster_size_at_formation
2020-11-19 10:37:13.980+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.minimum_core_cluster_size_at_runtime
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: metrics.graphite.enabled
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: metrics.prometheus.endpoint
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.raft_advertised_address
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: metrics.graphite.interval
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.discovery_type
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.transaction_advertised_address
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: dbms.backup.enabled
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: metrics.jmx.enabled
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.kubernetes.label_selector
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.kubernetes.service_port_name
2020-11-19 10:37:13.981+0000 WARN  Unrecognized setting. No declared setting with name: dbms.backup.listen_address
2020-11-19 10:37:13.982+0000 WARN  Unrecognized setting. No declared setting with name: causal_clustering.discovery_advertised_address
2020-11-19 10:37:13.982+0000 WARN  Unrecognized setting. No declared setting with name: metrics.prometheus.enabled
2020-11-19 10:37:13.982+0000 WARN  Unrecognized setting. No declared setting with name: metrics.csv.interval
2020-11-19 10:37:13.982+0000 WARN  Unrecognized setting. No declared setting with name: metrics.csv.enabled
2020-11-19 10:37:13.982+0000 INFO  Starting...
2020-11-19 10:37:16.746+0000 INFO  ======== Neo4j 4.1.3 ========
2020-11-19 10:37:32.437+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address. Error starting Neo4j database server at /data/databases
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@6920614' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.generate.ba` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
	... 5 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.generate.ba` is already in use.
	at org.neo4j.procedure.impl.ProcedureRegistry.register(ProcedureRegistry.java:87)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.register(GlobalProceduresRegistry.java:143)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.register(GlobalProceduresRegistry.java:93)
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:345)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	... 7 more
2020-11-19 10:37:32.438+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by felipeazv** [comment]
I found that the issue was related to the fact I was using the wrong folder for loading plugins (by default is /apoc/)
