### ISSUE TITLE
Standalone pod erroring out with lock issue in the very first run with a clean volume

### ISSUE THREAD

**Issue by chprasad** [neo4j-contrib/neo4j-helm#202]
Helm install of neo4j-4.2.7-2 chart with standalone set to `true` is resulting in a `Unable to obtain lock on file: /data/databases/store_lock` issue on the very first run with a clean volume. Re-run after cleaning up the volume once again results in the same error.

Here are the versions in my environment:

Kubernetes v1.19
Helm v3.6.0

**Comment by chprasad** [comment]
While looking into this, it'll be awesome if a related issue described at https://github.com/neo4j/docker-neo4j/issues/289 is also attended to.

**Comment by eastlondoner** [comment]
What Kubernetes implementation are you using (e.g. Minikube, Google Kubernetes Engine etc.).

In many cases the storage underlying persistent volumes is not automatically cleaned up e.g. GKE often leaves Google Cloud Compute Engine Persistent Disks in place even after a PersistentVolume is removed from GKE.

The underlying storage can be re-used, especially if the name of the persistent volume is the same - can you check that this isn't what is occurring ?

**Comment by chprasad** [comment]
I am using a custom cluster setup using `kubeadm` 1.19.7 with nodes running Ubuntu 20.04.1 LTS.  I am manually cleaning the underlying volume to test with a clean fresh volume.

I am suspecting a cascade of issues here,  rooted in: 
1. Auto-restarts at startup time due to events such as: apoc plugin download and install, password change, ...
2. Issue reported at https://github.com/neo4j/docker-neo4j/issues/289. 

To avoid auto-restart at start-up time, I turned off apoc plug install and also allowed helm chart to generate its own password. 

Even after that, I see multiple start banners. Also, I now see a conflicting set of error messages. One talking about socket binding problem (probably a red-herring) and another talking about lock issue (probably the root cause).

```
Configuration override prefix = <snipped>
Starting Neo4j CORE 0 on <snipped>.<snipped>.default.svc.cluster.local
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
Changed password for user 'neo4j'.
Directories in use:
home: /var/lib/neo4j
config: /var/lib/neo4j/conf
logs: /data/logs
plugins: /plugins
import: /var/lib/neo4j/import
data: /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
run: /var/lib/neo4j/run
Starting Neo4j.
2021-06-18 08:59:42.482+0000 INFO Starting...
2021-06-18 08:59:46.526+0000 INFO ======== Neo4j 4.2.7 ========
Configuration override prefix = <snipped>
Starting Neo4j CORE 0 on <snipped>.<snipped>.default.svc.cluster.local
Changed password for user 'neo4j'.
Directories in use:
home: /var/lib/neo4j
config: /var/lib/neo4j/conf
logs: /data/logs
plugins: /plugins
import: /var/lib/neo4j/import
data: /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
run: /var/lib/neo4j/run
Starting Neo4j.
2021-06-18 09:00:19.928+0000 INFO Starting...
2021-06-18 09:00:24.601+0000 INFO ======== Neo4j 4.2.7 ========
2021-06-18 09:00:36.197+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address.
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:207) ~[neo4j-4.2.7.jar:4.2.7]
...
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.LockerLifecycleAdapter@5f14a673' was successfully initialized, but failed to start. Please see the attached cause exception "No locks available".
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463) ~[neo4j-common-4.2.7.jar:4.2.7]
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) ~[neo4j-common-4.2.7.jar:4.2.7]
...
Caused by: org.neo4j.kernel.internal.locker.FileLockException: Unable to obtain lock on file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
at org.neo4j.kernel.internal.locker.Locker.storeLockException(Locker.java:175) ~[neo4j-kernel-4.2.7.jar:4.2.7]
at org.neo4j.kernel.internal.locker.Locker.unableToObtainLockException(Locker.java:168) ~[neo4j-kernel-4.2.7.jar:4.2.7]
at org.neo4j.kernel.internal.locker.Locker.checkLock(Locker.java:107) ~[neo4j-kernel-4.2.7.jar:4.2.7]
at org.neo4j.kernel.internal.locker.GlobalFileLocker.checkLock(GlobalFileLocker.java:58) ~[neo4j-kernel-4.2.7.jar:4.2.7]
at org.neo4j.kernel.internal.locker.GlobalLocker.checkLock(GlobalLocker.java:28) ~[neo4j-kernel-4.2.7.jar:4.2.7]
...
```

**Comment by chprasad** [comment]
https://github.com/neo4j/neo4j/issues/10625 provided the answer. I was using a NFS mount. Setting the `no lock` option on the mount fixed the issue.
